apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  labels:
    app: discovery-service
    profile: prod
spec:
  selector:
    matchLabels:
      app: discovery-service
      profile: prod
  # 롤링 업데이트:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # 롤링 업데이트시 스케일아웃할 최대 pod 수
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      name: discovery-pod
      labels:
        app: discovery-service
        profile: prod
    spec:
      containers:
        - name: discovery-deployment
          image: ${ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
      restartPolicy: Always

